version: '3.8'
services:
  postgres:
    image: docker.io/library/postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /pgtmpfs
      POSTGRES_DB: atlas-repro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
    tmpfs: /pgtmpfs
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready --username=postgres
      interval: 1s
      retries: 100
